#+title: Fedora 40 Workstation Bootstrap
#+PROPERTY: header-args:bash :tangle scripts/fedora-40-workstation.sh :comments org :mkdirp yes :shebang "#!/bin/bash" :eval no

* note
For about a month I gave Gnome a try on Fedora 40 Workstation. It just didn't click with me, however. I'm preserving my bootstrap script here for future enjoyment. NOTE: not listed here is that I used PaperWM which is installed via Gnome Extension, and those are installed, at least as far as I can tell, via browser. There's likely a command line way to do it but I didn't dig in that far. NOTE NOTE: I actually really liked PaperWM, it's just the rest of Gnome I kind of bounced off of.

* system setup/tools
** set up flathub remote
#+BEGIN_SRC bash
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
#+END_SRC
** rpmfusion/media packages
#+BEGIN_SRC bash
sudo dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
sudo dnf config-manager --enable fedora-cisco-openh264
sudo dnf swap -y ffmpeg-free ffmpeg --allowerasing
sudo dnf update -y @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin
sudo dnf swap -y mesa-va-drivers mesa-va-drivers-freeworld
sudo dnf swap -y mesa-vdpau-drivers mesa-vdpau-drivers-freeworld
sudo dnf install -y libva-utils libheif-tools
#+END_SRC
** tailscale
Note: to finish Tailscale setup, run ~sudo tailscale up~ when ready.
#+BEGIN_SRC bash
sudo dnf config-manager --add-repo https://pkgs.tailscale.com/stable/fedora/tailscale.repo
sudo dnf install -y tailscale
sudo systemctl enable --now tailscaled
#+END_SRC
* gui applications
** steam
#+BEGIN_SRC bash
flatpak install -y flathub com.valvesoftware.Steam
sudo dnf install -y steam-devices
#+END_SRC
** discord
#+BEGIN_SRC bash
flatpak install flathub com.discordapp.Discord
#+END_SRC
** fractal (matrix)
#+BEGIN_SRC bash
flatpak install flathub org.gnome.Fractal
#+END_SRC
** foliate
#+BEGIN_SRC bash
flatpak install flathub com.github.johnfactotum.Foliate
#+END_SRC
** 1password
#+BEGIN_SRC bash
sudo dnf install -y https://downloads.1password.com/linux/rpm/stable/x86_64/1password-latest.rpm
#+END_SRC
** doomemacs
#+BEGIN_SRC bash
sudo dnf install -y emacs fd-find ripgrep shellcheck shfmt
rm -rf ~/.emacs.d
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
~/.config/emacs/bin/doom install
#+END_SRC
*** module prereqs
required for:
- mu4e
- markdown-preview
#+BEGIN_SRC bash
sudo dnf install -y isync maildir-utils pandoc
#+END_SRC
** localsend
#+BEGIN_SRC bash
flatpak install -y flathub org.localsend.localsend_app
#+END_SRC
** image editing
#+BEGIN_SRC bash
sudo dnf install -y pinta krita
#+END_SRC
** terminal
#+BEGIN_SRC bash
sudo dnf install -y alacritty
#+END_SRC
** video
mpv frontend
#+BEGIN_SRC
flatpak install flathub io.github.celluloid_player.Celluloid
#+END_SRC
** misc
a nice little pile of gnome circle applications
#+BEGIN_SRC bash
flatpak install flathub com.rafaelmardojai.Blanket
flatpak install flathub de.haeckerfelix.Shortwave
flatpak install flathub app.fotema.Fotema
flatpak install flathub info.febvre.Komikku
flatpak install flathub dev.bragefuglseth.Fretboard
flatpak install flathub org.gnome.design.Emblem
flatpak install flathub page.kramo.Cartridges
flatpak install flathub net.nokyan.Resources
flatpak install flathub de.haeckerfelix.Fragments
flatpak install flathub dev.geopjr.Tuba
#+END_SRC
** easyeffects
Installs EasyEffects with presets for the framework 13 speakers
#+BEGIN_SRC bash
flatpak install flathub com.github.wwmm.easyeffects
TMP=$(mktemp -d) && \
CFG=${XDG_CONFIG_HOME:-~/.config}/easyeffects && \
mkdir -p "$CFG" && \
curl -Lo $TMP/fwdsp.zip https://github.com/cab404/framework-dsp/archive/refs/heads/master.zip && \
unzip -d $TMP $TMP/fwdsp.zip 'framework-dsp-master/config/*/*' && \
sed -i 's|%CFG%|'$CFG'|g' $TMP/framework-dsp-master/config/*/*.json && \
cp -rv $TMP/framework-dsp-master/config/* $CFG && \
rm -rf $TMP
#+END_SRC
* cli/misc tools
** playball! (mlb)
#+BEGIN_SRC bash
sudo dnf install -y nodejs
sudo npm install -g playball
#+END_SRC
** rust
#+BEGIN_SRC bash
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
#+END_SRC
** haskell
#+BEGIN_SRC bash
sudo dnf install -y stack
#+END_SRC
** the rest
#+BEGIN_SRC bash
sudo dnf install -y vim stow htop iftop fzf lm_sensors
#+END_SRC
* gnome customizations
** extensions/tweaks
#+BEGIN_SRC bash
sudo dnf install -y gnome-tweaks
sudo dnf install -y gnome-extensions-app
sudo dnf install -y gnome-shell-extension-appindicator
sudo dnf install -y gnome-shell-extension-blur-my-shell
sudo dnf install -y gnome-shell-extension-caffeine
sudo dnf install -y gnome-shell-extension-just-perfection
sudo dnf install -y gnome-shell-extension-openweather
#+END_SRC
** gtk3 dark theme
Some applications (like emacs or 1password) don't support gtk4 so we need this package to enable dark mode on "legacy" apps (see gnome-tweaks)
#+BEGIN_SRC bash
sudo dnf install -y adw-gtk3-theme
#+END_SRC
** preinstalled software I don't use/want/like
#+BEGIN_SRC bash
sudo dnf remove -y gnome-boxes
sudo dnf remove -y libreoffice*
sudo dnf remove -y totem
sudo dnf remove -y rhythmbox
#+END_SRC
